[phases.setup]
nixPkgs = ["dotnet-sdk"]

[phases.build]
cmds = [
  "dotnet --version",
  "dotnet restore MaiAmTinhThuong.csproj",
  "dotnet build MaiAmTinhThuong.csproj -c Release",
  "dotnet publish MaiAmTinhThuong.csproj -c Release -o /app"
]

[start]
cmd = "dotnet /app/MaiAmTinhThuong.dll"

